### ISSUE TITLE
Update django-elastic-appsearch to use the new official python client 

### ISSUE THREAD

**Issue by CorrosiveKid** [infoxchange/django_elastic_appsearch#109]
The official [app-search-python client](https://github.com/elastic/app-search-python) used by this package is being deprecated. They are introducing a [new official python client](https://github.com/elastic/enterprise-search-python) which encapsulates client methods for the entire enterprise-search suite, which is currently in beta.

**Comment by IXAMat** [comment]
Resolved by https://github.com/infoxchange/django_elastic_appsearch/pull/176
